language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.1.0
  - 2.1.0
  - 2.2.0
gemfile:
  - Gemfile
  - gemfiles/rails-3.2.gemfile
  - gemfiles/rails-4.1.gemfile
  - gemfiles/rails-4.2.gemfile
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails-master.gemfile
    - rvm: 2.2.0
      gemfile: gemfiles/rails-3.2.gemfile
  include:
    - rvm: 2.2.0
      gemfile: gemfiles/rails-master.gemfile
